### ISSUE TITLE
request

### ISSUE THREAD

**Issue by bawet27** [Rizky878/rzky-multidevice#20]
tambahin antilink min :v

**Comment by Rizky878** [comment]
oke, otw

**Comment by Natx-C** [comment]
> oke, otw

ini fb iso kah bang?, btw sialan kepencet unstart

**Comment by Rizky878** [comment]
> > oke, otw
> 
> ini fb iso kah bang?, btw sialan kepencet unstart

bisa, kalo ga bisa mungkin aja videonya private
