### ISSUE TITLE
REQUEST

### ISSUE THREAD

**Issue by Natx-C** [Rizky878/rzky-multidevice#46]
tambahin game lagi bang hehehe

**Comment by Rizky878** [comment]
game apa

**Comment by SafiiGazz** [comment]
Tambahin game kontol bang

**Comment by Natx-C** [comment]
> game apa

kaya caklontong,tekateki gitu bang mwhehe

**Comment by Natx-C** [comment]
> Tambahin game kontol bang

astaghfirullah

**Comment by Rizky878** [comment]
> > game apa
> 
> kaya caklontong,tekateki gitu bang mwhehe

oke²
