### ISSUE TITLE
Why don’t u add mongodb to save the contacts

### ISSUE THREAD

**Issue by Das-kun** [Rizky878/rzky-multidevice#47]

**Comment by Rizky878** [comment]
because I think it will make it difficult for users of this script to run it, so because of that I just keep it simple, and the rest is up to you guys to add anything

**Comment by Das-kun** [comment]
> because I think it will make it difficult for users of this script to run it, so because of that I just keep it simple, and the rest is up to you guys to add anything

Ohhhh

**Comment by Das-kun** [comment]
> because I think it will make it difficult for users of this script to run it, so because of that I just keep it simple, and the rest is up to you guys to add anything

Btw can I get your phone number or any group link
