### ISSUE TITLE
ini kenapa error

### ISSUE THREAD

**Issue by NugrahaMP** [Rizky878/rzky-multidevice#53]
![Screenshot_2022-09-20-23-36-06-194_com.gbwhatsapp.jpg](https://user-images.githubusercontent.com/86095279/191301904-ef509bd7-6884-4a9e-8ed2-394a262197be.jpg)

dari tadi gini mulu dia. tolong dong

**Comment by Rizky878** [comment]
ubah di config.json thumbvideo menjadi link video kmu
